// Author: kouwei
#pragma once
#include "CommMsg.h"


#define WM_UNIVERSAL_MESSAGE_SCOPE_BEGIN	(WM_USER + 0xe000 - 1)
#define WM_UNIVERSAL_MESSAGE_SCOPE_END		(0xffff)

MESSAGE_NUMBER_SCOPE_BEGIN(UNIVERSAL)

	// 公共消息号
	DEFINE_MESSAGE_SCOPE(SODALIB,			0x200)
	DEFINE_MESSAGE_SCOPE(DUILIB,			0x200)
	DEFINE_MESSAGE_SCOPE(DUILite,			0x200)
	DEFINE_MESSAGE_SCOPE(COMMONLIB,			0x200)

MESSAGE_NUMBER_SCOPE_END(UNIVERSAL)
